stages:
  - build

.rules_master_auto_run: &rules_master_auto_run
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    when: never
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    when: always
  - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
    when: manual

.tags_builder: &tags_builder
  - builder

.tags_deployer: &tags_deployer
  - deployer

build-job:
  stage: build
  image: node:16.20
  timeout: 30 minutes
  rules: *rules_master_auto_run
  tags: *tags_deployer
  script:
    - npm install && npm run build
    - npm set "registry=https://art.rambler.ru/api/npm/listim-npm/"
    - npm set "//art.rambler.ru/api/npm/listim-npm/:_password=${REGISTRY_PASSWORD}"
    - npm set "//art.rambler.ru/api/npm/listim-npm/:username=${REGISTRY_USER}"
    - npm set "//art.rambler.ru/api/npm/listim-npm/:email=devnull@rambler-co.ru"
    - npm set "//art.rambler.ru/api/npm/listim-npm/:always-auth=true"
    - apt update
    - apt install -y less
    - less ~/.npmrc
    - npm publish --access=public
