version: '3.7'

services:
  frontend:
    build:
      context: ./
      dockerfile: docker/Local/Dockerfile
    volumes:
      - ./:/var/www/html/frontend
    ports:
      - '8090:8090'
    tty: true
