// Места для SVG схемы зала

// const seats = {
//   1: {
//     id: 1,
//     row: "1",
//     seat: "1",
//     x: 25,
//     y: 25,
//     bg_color: "#fff",
//     border_color: ["#e30611", "#ff000b"],
//     tooltip: null,
//     reserved_by_user: false,
//     sell_channels: {
//       is_widget: true,
//       is_api: true,
//       is_cashbox: true,
//     },
//     price: "100.00",
//     status: "available",
//     sector: {
//       id: 1,
//       name: "Партер",
//     },
//     event_place: {
//       id: 506,
//       price: "100.00",
//       event: {
//         id: 10,
//       },
//     },
//   },
//   // ...
// };

const MAP_PLACES = {
  1: {
    id: 1,
    row: "1",
    seat: "1",
    x: 25,
    y: 25,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 506,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  2: {
    id: 2,
    row: "2",
    seat: "1",
    x: 50,
    y: 25,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 507,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  3: {
    id: 3,
    row: "3",
    seat: "1",
    x: 75,
    y: 25,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 508,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  4: {
    id: 4,
    row: "4",
    seat: "1",
    x: 100,
    y: 25,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 509,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  5: {
    id: 5,
    row: "5",
    seat: "1",
    x: 125,
    y: 25,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 510,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  6: {
    id: 6,
    row: "6",
    seat: "1",
    x: 150,
    y: 25,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 511,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  7: {
    id: 7,
    row: "7",
    seat: "1",
    x: 175,
    y: 25,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 512,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  8: {
    id: 8,
    row: "8",
    seat: "1",
    x: 200,
    y: 25,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 513,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  9: {
    id: 9,
    row: "9",
    seat: "1",
    x: 225,
    y: 25,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 514,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  10: {
    id: 10,
    row: "10",
    seat: "1",
    x: 250,
    y: 25,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 515,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  11: {
    id: 11,
    row: "1",
    seat: "2",
    x: 25,
    y: 50,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 516,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  12: {
    id: 12,
    row: "2",
    seat: "2",
    x: 50,
    y: 50,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 517,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  13: {
    id: 13,
    row: "3",
    seat: "2",
    x: 75,
    y: 50,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 518,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  14: {
    id: 14,
    row: "4",
    seat: "2",
    x: 100,
    y: 50,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 519,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  15: {
    id: 15,
    row: "5",
    seat: "2",
    x: 125,
    y: 50,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 520,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  16: {
    id: 16,
    row: "6",
    seat: "2",
    x: 150,
    y: 50,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 521,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  17: {
    id: 17,
    row: "7",
    seat: "2",
    x: 175,
    y: 50,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 522,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  18: {
    id: 18,
    row: "8",
    seat: "2",
    x: 200,
    y: 50,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 523,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  19: {
    id: 19,
    row: "9",
    seat: "2",
    x: 225,
    y: 50,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 524,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  20: {
    id: 20,
    row: "10",
    seat: "2",
    x: 250,
    y: 50,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 525,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  21: {
    id: 21,
    row: "1",
    seat: "3",
    x: 25,
    y: 75,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 526,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  22: {
    id: 22,
    row: "2",
    seat: "3",
    x: 50,
    y: 75,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 527,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  23: {
    id: 23,
    row: "3",
    seat: "3",
    x: 75,
    y: 75,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 528,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  24: {
    id: 24,
    row: "4",
    seat: "3",
    x: 100,
    y: 75,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 529,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  25: {
    id: 25,
    row: "5",
    seat: "3",
    x: 125,
    y: 75,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 530,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  26: {
    id: 26,
    row: "6",
    seat: "3",
    x: 150,
    y: 75,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 531,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  27: {
    id: 27,
    row: "7",
    seat: "3",
    x: 175,
    y: 75,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 535,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  28: {
    id: 28,
    row: "8",
    seat: "3",
    x: 200,
    y: 75,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 532,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  29: {
    id: 29,
    row: "9",
    seat: "3",
    x: 225,
    y: 75,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 533,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  30: {
    id: 30,
    row: "10",
    seat: "3",
    x: 250,
    y: 75,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 534,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  31: {
    id: 31,
    row: "1",
    seat: "4",
    x: 25,
    y: 100,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 536,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  32: {
    id: 32,
    row: "2",
    seat: "4",
    x: 50,
    y: 100,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 537,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  33: {
    id: 33,
    row: "3",
    seat: "4",
    x: 75,
    y: 100,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 538,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  34: {
    id: 34,
    row: "4",
    seat: "4",
    x: 100,
    y: 100,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 539,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  35: {
    id: 35,
    row: "5",
    seat: "4",
    x: 125,
    y: 100,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 540,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  36: {
    id: 36,
    row: "6",
    seat: "4",
    x: 150,
    y: 100,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 541,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  37: {
    id: 37,
    row: "7",
    seat: "4",
    x: 175,
    y: 100,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 542,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  38: {
    id: 38,
    row: "8",
    seat: "4",
    x: 200,
    y: 100,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 543,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  39: {
    id: 39,
    row: "9",
    seat: "4",
    x: 225,
    y: 100,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 544,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  40: {
    id: 40,
    row: "10",
    seat: "4",
    x: 250,
    y: 100,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 545,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  41: {
    id: 41,
    row: "1",
    seat: "5",
    x: 25,
    y: 125,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 546,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  42: {
    id: 42,
    row: "2",
    seat: "5",
    x: 50,
    y: 125,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 547,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  43: {
    id: 43,
    row: "3",
    seat: "5",
    x: 75,
    y: 125,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 548,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  44: {
    id: 44,
    row: "4",
    seat: "5",
    x: 100,
    y: 125,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 549,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  45: {
    id: 45,
    row: "5",
    seat: "5",
    x: 125,
    y: 125,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 550,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  46: {
    id: 46,
    row: "6",
    seat: "5",
    x: 150,
    y: 125,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 551,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  47: {
    id: 47,
    row: "7",
    seat: "5",
    x: 175,
    y: 125,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 552,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  48: {
    id: 48,
    row: "8",
    seat: "5",
    x: 200,
    y: 125,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 553,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  49: {
    id: 49,
    row: "9",
    seat: "5",
    x: 225,
    y: 125,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 554,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  50: {
    id: 50,
    row: "10",
    seat: "5",
    x: 250,
    y: 125,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 555,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  51: {
    id: 51,
    row: "1",
    seat: "6",
    x: 25,
    y: 150,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 556,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  52: {
    id: 52,
    row: "2",
    seat: "6",
    x: 50,
    y: 150,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 557,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  53: {
    id: 53,
    row: "3",
    seat: "6",
    x: 75,
    y: 150,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 558,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  54: {
    id: 54,
    row: "4",
    seat: "6",
    x: 100,
    y: 150,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 559,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  55: {
    id: 55,
    row: "5",
    seat: "6",
    x: 125,
    y: 150,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 560,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  56: {
    id: 56,
    row: "6",
    seat: "6",
    x: 150,
    y: 150,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 561,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  57: {
    id: 57,
    row: "7",
    seat: "6",
    x: 175,
    y: 150,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 562,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  58: {
    id: 58,
    row: "8",
    seat: "6",
    x: 200,
    y: 150,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 563,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  59: {
    id: 59,
    row: "9",
    seat: "6",
    x: 225,
    y: 150,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 564,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  60: {
    id: 60,
    row: "10",
    seat: "6",
    x: 250,
    y: 150,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 565,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  61: {
    id: 61,
    row: "1",
    seat: "7",
    x: 25,
    y: 175,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 566,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  62: {
    id: 62,
    row: "2",
    seat: "7",
    x: 50,
    y: 175,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 567,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  63: {
    id: 63,
    row: "3",
    seat: "7",
    x: 75,
    y: 175,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 568,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  64: {
    id: 64,
    row: "4",
    seat: "7",
    x: 100,
    y: 175,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 569,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  65: {
    id: 65,
    row: "5",
    seat: "7",
    x: 125,
    y: 175,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 570,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  66: {
    id: 66,
    row: "6",
    seat: "7",
    x: 150,
    y: 175,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 571,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  67: {
    id: 67,
    row: "7",
    seat: "7",
    x: 175,
    y: 175,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 572,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  68: {
    id: 68,
    row: "8",
    seat: "7",
    x: 200,
    y: 175,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 573,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  69: {
    id: 69,
    row: "9",
    seat: "7",
    x: 225,
    y: 175,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 574,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  70: {
    id: 70,
    row: "10",
    seat: "7",
    x: 250,
    y: 175,
    bg_color: "#fff",
    border_color: ["#e30611", "#ff000b"],
    tooltip: null,
    reserved_by_user: false,
    sell_channels: {
      is_widget: true,
      is_api: true,
      is_cashbox: true,
    },
    price: "100.00",
    status: "available",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: {
      id: 575,
      price: "100.00",
      event: {
        id: 10,
      },
    },
  },
  71: {
    id: 71,
    row: "1",
    seat: "8",
    x: 25,
    y: 200,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  72: {
    id: 72,
    row: "2",
    seat: "8",
    x: 50,
    y: 200,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  73: {
    id: 73,
    row: "3",
    seat: "8",
    x: 75,
    y: 200,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  74: {
    id: 74,
    row: "4",
    seat: "8",
    x: 100,
    y: 200,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  75: {
    id: 75,
    row: "5",
    seat: "8",
    x: 125,
    y: 200,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  76: {
    id: 76,
    row: "6",
    seat: "8",
    x: 150,
    y: 200,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  77: {
    id: 77,
    row: "7",
    seat: "8",
    x: 175,
    y: 200,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  78: {
    id: 78,
    row: "8",
    seat: "8",
    x: 200,
    y: 200,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  79: {
    id: 79,
    row: "9",
    seat: "8",
    x: 225,
    y: 200,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  80: {
    id: 80,
    row: "10",
    seat: "8",
    x: 250,
    y: 200,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  81: {
    id: 81,
    row: "1",
    seat: "9",
    x: 25,
    y: 225,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  82: {
    id: 82,
    row: "2",
    seat: "9",
    x: 50,
    y: 225,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  83: {
    id: 83,
    row: "3",
    seat: "9",
    x: 75,
    y: 225,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  84: {
    id: 84,
    row: "4",
    seat: "9",
    x: 100,
    y: 225,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  85: {
    id: 85,
    row: "5",
    seat: "9",
    x: 125,
    y: 225,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  86: {
    id: 86,
    row: "6",
    seat: "9",
    x: 150,
    y: 225,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  87: {
    id: 87,
    row: "7",
    seat: "9",
    x: 175,
    y: 225,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  88: {
    id: 88,
    row: "8",
    seat: "9",
    x: 200,
    y: 225,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  89: {
    id: 89,
    row: "9",
    seat: "9",
    x: 225,
    y: 225,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  90: {
    id: 90,
    row: "10",
    seat: "9",
    x: 250,
    y: 225,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  91: {
    id: 91,
    row: "1",
    seat: "10",
    x: 25,
    y: 250,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  92: {
    id: 92,
    row: "2",
    seat: "10",
    x: 50,
    y: 250,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  93: {
    id: 93,
    row: "3",
    seat: "10",
    x: 75,
    y: 250,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  94: {
    id: 94,
    row: "4",
    seat: "10",
    x: 100,
    y: 250,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  95: {
    id: 95,
    row: "5",
    seat: "10",
    x: 125,
    y: 250,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  96: {
    id: 96,
    row: "6",
    seat: "10",
    x: 150,
    y: 250,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  97: {
    id: 97,
    row: "7",
    seat: "10",
    x: 175,
    y: 250,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  98: {
    id: 98,
    row: "8",
    seat: "10",
    x: 200,
    y: 250,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  99: {
    id: 99,
    row: "9",
    seat: "10",
    x: 225,
    y: 250,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
  100: {
    id: 100,
    row: "10",
    seat: "10",
    x: 250,
    y: 250,
    bg_color: "#999",
    border_color: "#808080",
    tooltip: null,
    reserved_by_user: false,
    sell_channels: [],
    price: null,
    status: "closed",
    sector: {
      id: 1,
      name: "Партер",
    },
    event_place: null,
  },
};

export { MAP_PLACES };
